language: ruby
bundler_args: --without development
before_install: gem install bundler --pre
script: "bundle exec rspec spec"
rvm:
  - 1.8.7
  - rbx-18mode
  - rbx-19mode
  - ree
  - jruby-18mode
  - jruby-19mode
  - 1.9.2
  - 1.9.3
  - jruby-head
  - ruby-head
notifications:
  recipients:
    - michaelklishin@me.com
