language: ruby
bundler_args: --without development
script: "bundle exec rspec spec"
rvm:
  - 2.0
  - 2.1
  - 2.2  
  - ruby-head
notifications:
  recipients:
    - michael@rabbitmq.com
matrix:
  allow_failures:
    - rvm: ruby-head
