# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
bundler_args: --without development
script: "bundle exec rspec spec"
rvm:
  - 1.8.7
  - rbx-2.0
  - ree
  - jruby
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  recipients:
    - michaelklishin@me.com
