# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
bundler_args: --without development
script: "bundle exec rspec spec"
rvm:
  - 1.8.7
  - 1.8.7-p249
  - 1.9.2
  - jruby
  - rbx-2.0
  - ree
  - ruby-head
notifications:
  recipients:
    - jakub@rabbitmq.com
    - michaelklishin@me.com
    - markizko@gmail.com
