language: ruby
bundler_args: --without development
script: "bundle exec rspec spec"
rvm:
  - 1.8.7
  - rbx-18mode
  - rbx-19mode
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
notifications:
  recipients:
    - michael@novemberain.com
